name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose --manifest-path person-sensor/Cargo.toml
      - name: Run tests
        run: cargo test --verbose --manifest-path person-sensor/Cargo.toml

  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Clippy
        run: cargo clippy --manifest-path person-sensor/Cargo.toml -- -D warnings
